#Written by Eric Bell
#1/19/17
#
#proccsv.py processes the .csv file generated by chemmine.R by removing the quotes around the bitstring and appending the binding affinity

import sys
from re import search

args = sys.argv
if len(args)<3 or len(args)>4:
    print("Incorrect number of arguments")
    exit(1)

try:
    f = open(args[1],"r") #argument 1 is the filename of the .csv to be processed
    if len(args) > 2:
        w = open(args[3],"w") #argument 3 is the name of the output .csv, defaults to "proc.csv"
    else:
        w = open("proc.csv","w")
except:
    print("Error opening file")
    exit(1)

#fetchEnergy searches the text file (a res.txt) for the molecule mol and returns its binding affinity
def fetchEnergy(mol):
    fi = open(args[2],"r") #argument 2 is the filename of the res.txt-like text file that contains the molecules and their predicted binding affinities
    grepline=""
    for line in fi:
        if search(mol,line):
            grepline=line
            break
    if grepline=="":
        return None
    else:
        try:
            energy=grepline.split(" ")[1]
            return energy
        except:
            print("There was a problem processing molecule "+mol+": "+str(sys.exc_info()[0]))
            return None

f.readline() #first line is "x", get rid of it

#rewrite each line of the input csv by removing quotes around the values and appending the binding affinity
for line in f:
    parts = line.split(",")
    for i,part in enumerate(parts):
        parts[i]=part.replace("\"","")
    parts.append(fetchEnergy(parts[0]))
    w.write(parts[0]+","+parts[1].strip()+","+parts[2])

f.close()
w.close()
